version: 0.2

env:
  variables:
    AWS_REGION: "ap-southeast-1"
    AWS_ACCOUNT_ID: "852288348919"
    REPO_NAME: "ml-infra-pipelines-train-dev"

phases:
  pre_build:
    commands:
      - echo Login to ecr
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com 
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.ap-southeast-1.amazonaws.com/${REPO_NAME} -f train/Dockerfile . 
      - echo Pushing the Docker image...
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:latest
  post_build:
    commands:
      - echo "Running Terraform Apply"
      - terraform apply -auto-approve
      - echo "Executing the SageMaker training job"
      - pip install sagemaker
      - python train/run_job.py --file_location "s3://ml-infra-pipelines-dev/sample/training/iris.csv" --model_package_group_name ml-infra-iris-predictor